# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Sharat Oommen
title: Product Engineer
email: sharatoommen94@gmail.com
website: sharat94.github.io

# Social links
twitter_username: sharathey94
github_username:  sharat94
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: sharat_94
linkedin_username: sharat94
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# Additional buttons
additional_links:
- title: Download Resume
  icon: fas fa-file-download
  url: https://drive.google.com/file/d/14BA0Cs9rZk42OmBNyNkkjd_YJLhSV3DD/view?usp=drive_link

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, My name is Sharat Oommen and I'm a freelance product engineer. I have worked at a number of companies gaining teamwork and leadership skills.I am deeply passionate about building products which adds value to people's lives.
  I have worked primarily with Ruby on Rails, Python, Golang and React.
# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Gaming
   - Reading books (loonshots, shoe dog to name a few)
   - Cooking (Mostly south indian specialities)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
